### PR TITLE
Begin materialize

### PR DESCRIPTION
**Pull request by cstoafer**
I briefly looked into options for a front-end framework.  I think Jiaqi mentioned [materialize](http://materializecss.com/getting-started.html), so I figure the cool kids are using it.  

It was quick to setup, so we can change it if we want to.

Also considered Bootstrap, which I'd be fine with, or [Foundation](http://foundation.zurb.com/frameworks-docs.html), which I've used before and like, but it lacks some community support when you have weird problems.

### CODE REVIEW

**Comment by cstoafer** [comment]
Should I gitignore more of these files?  Front-end always confuses me.

**Comment by sharnett** [comment]
Dan (@yoursweater) used Materialize in his bootcamp, so I think it is indeed what the cool kids are using. Not saying Dan is cool, just that the bootcamp was pretty legit. Materialize looks pretty sweet too.

**Comment by cstoafer** [comment]
Yeah, it seems like materialize has a good look, like Bootstrap, with the customizability of zurb Foundation.

**Comment by cstoafer** [comment]
The content from this PR are included in #5, making it superfluous.

**Pull request closed without merging**
