### PR TITLE
Heroku with postgres

### LINKED ISSUE #1: Deploy simple web app to Heroku
Can be Flask or Django or other.

Contains:
- Input text box for zip code
- Submit button
- Display area for representative names and phone numbers

Does NOT need to function for issue to be closed.

### PR DESCRIPTION
**Pull request by cstoafer**
- Removes sqlite
- Adds migration for postgres, but empty database.
- Ready for API to return representative contact info.
- Can see online at: https://influencr-stage.herokuapp.com/

closes #1

### CODE REVIEW

**Comment by cstoafer** [comment]
- I included `.env` because I set some environmental variables in there, but it also uses `conda envs` which others might not use.  Should I not include this file?
- Anything in the `migrations/` folder was automatically generated.  It needs to be included to keep the database generated for the Heroku app.

**Comment by suddensleep** [comment]
thoughts on .env stuff:

environmental variables like APP_SETTINGS seem to be useful and helpful, but i have no sense whether using conda for virtual environments is the norm or not. i personally use virtualenv (with an .env file), but don't know if there's a way to abstract an env file that would work for both.

one thing we might also look into if we choose conda envs is whether we want to keep a requirements.txt file or an environment.yml file: see [this](http://stiglerdiet.com/blog/2015/Nov/24/my-python-environment-workflow-with-conda/) funky fresh blog post.

**Comment by cstoafer** [comment]
I updated the `.env` file to allow for allowing other types of environments.  Just make your own `.activateenv` file with the script to activate your favorite env.

We should stick with `requirements.txt` because that is what Heroku uses.

I feel like I just talked to you about this stuff.

**Comment by cstoafer** [comment]
Merging because this adds a good base to begin the project.  We can update structure and fix problems with future PRs.

**Pull request merged**
